sudo: false
language: python
python:
  - "2.7"
# Use firefox with xvfb to run a browser where necessary
# for selenium
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
install:
    - pip install -r requirements.txt
script:
    # Run unit tests and calculate code coverage.
    - coverage run --source client_wrapper -m unittest discover
    # Check that source has correct formatting.
    - yapf --diff --recursive --style google ./
    # Run static analysis for Python bugs/cruft.
    - pyflakes client_wrapper/*.py tests/*.py
after_success:
    coveralls

