sudo: false
language: python
python:
  - "2.7"
install:
    # Requirements needed to run application
    - pip install -r requirements.txt
    # Requirements needed to run application tests
    - pip install -r dev_requirements.txt
    # Requirements needed for Travis CI
    - pip install coveralls==1.1
script:
    ./build
after_success:
    coveralls

